default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRESQL_ADDRESS'] %>
  pool: 5
  username: <%= ENV["POSTGRESQL_USERNAME"] %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>

development:
  <<: *default
  database: be-vimmer_development

test:
  <<: *default
  database: be-vimmer_test
